name: Main

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Replace release yml
      - name: spicy copy
        run: cp .github/other-release.yml .github/release.yml
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
